### ISSUE TITLE
[s-meiser.de] Add job outputs for to control job execution

### ISSUE THREAD

**Issue by s-meiser** [s-meiser/s-meiser.de#1]
Add job outputs (https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) for to control job execution while using if condidions (https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)

```sh
if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
```

IF Example
```sh
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
```

Job Outputs Example
```
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
```
